#!/bin/bash

# This copies in the bears.json
# from asciishop when changes are
# made

tmux select-pane -T "bears.json Loader"
cd /Users/alan/Downloads
watchexec -p --filter "ascii-shop.json" --fs-events create mv -- ascii-shop.json "/Users/alan/workshop/asciibear/html/bears.json"




